### ISSUE TITLE
Minor Code Smell: Unused Variable in Authenticator Test

### ISSUE THREAD

**Issue by aaron-wilson-bfg** [bigfishgames/GameBenchAPI-PyClient#27]
**Describe the bug**
The auth_data variable in test_auth_token_returned() is unused.

**To Reproduce**
https://sonarcloud.io/project/issues?id=bigfishgames_GameBenchAPI&issues=AWoxN32TK1LJlmpkYAwD&open=AWoxN32TK1LJlmpkYAwD

**Comment by tristan-fickes-bfg** [comment]
When you reload SonarCloud are you still seeing this un-used variable show up?  When I go to the Sonar Cloud site it's not showing any issues now: https://sonarcloud.io/project/issues?id=bigfishgames_GameBenchAPI&resolved=false

Also not seeing that variable in the module so it's possible it got fixed in a different branch since fixing this.  Just want to verify what you are seeing though before closing the issue.

**Comment by aaron-wilson-bfg** [comment]
> When you reload SonarCloud are you still seeing this un-used variable show up? When I go to the Sonar Cloud site it's not showing any issues now: https://sonarcloud.io/project/issues?id=bigfishgames_GameBenchAPI&resolved=false
> 
> Also not seeing that variable in the module so it's possible it got fixed in a different branch since fixing this. Just want to verify what you are seeing though before closing the issue.

It is showing as fixed.

**Comment by aaron-wilson-bfg** [comment]
https://sonarcloud.io/project/issues?id=bigfishgames_GameBenchAPI&resolutions=FIXED

**Comment by tristan-fickes-bfg** [comment]
Oh cool didn't even see that fixed label!  Cool, closing the issue.
